program: main.py
project: cifar10
entity: anonymity
name: cifar10-final
method: grid
metric:
  goal: maximize
  name: best/test_accuracy
parameters:
  dropout_res:
    value: 0.1
  dropout_local:
    value: 0.1
  dropout_ff:
    value: 0.1
  base_lr:
    value: 0.005
  weight_decay:
    value: 0.01

  reweigh_self:
    value: 2
  jk:
    value: 0
  init_pe_dim:
    value: 32
  more_mapping:
    value: 1
  cfg:
    value: configs/GSSC/cifar10-GSSC.yaml
  name_tag:
    value: random
  log_code:
    value: 0
  device:
    value: 0
  seed:
    values: [0, 1, 2, 3, 4]
