program: main.py
project: CLUSTER
entity: anonymity
name: cluster-final
method: grid
metric:
  goal: maximize
  name: best/test_accuracy-SBM
parameters:
  dropout_res:
    value: 0.3
  dropout_local:
    value: 0.3
  dropout_ff:
    value: 0.1
  base_lr:
    values: [0.001, 0.002, 0.003]
  weight_decay:
    values: [0.1, 0.2, 0.001]

  reweigh_self:
    value: 2
  jk:
    value: 1
  init_pe_dim:
    value: 32
  more_mapping:
    value: 1
  cfg:
    value: configs/GSSC/cluster-GSSC.yaml
  name_tag:
    value: random
  log_code:
    value: 0
  device:
    value: 0
  seed:
    values: [0, 1, 2, 3, 4]
