program: main.py
project: molhiv
entity: anonymity
name: molhiv-final
method: grid
metric:
  goal: maximize
  name: best/test_auc
parameters:
  dropout_res:
    value: 0.0
  dropout_local:
    value: 0.3
  dropout_ff:
    value: 0.0
  weight_decay:
    values: [0.1, 1.0e-3, 1.0e-5]
  base_lr:
    values: [0.001, 0.002, 0.0005]

  reweigh_self:
    value: 2
  jk:
    value: 0
  init_pe_dim:
    value: 32
  more_mapping:
    value: 1
  cfg:
    value: configs/GSSC/ogbg-molhiv-GSSC.yaml
  name_tag:
    value: random
  log_code:
    value: 0
  device:
    value: 0
  seed:
    values: [0, 1, 2, 3, 4]
