program: main.py
project: LRGB
entity: anonymity
name: vocsuperpixels-final
method: grid
metric:
  goal: maximize
  name: best/test_f1
parameters:
  dropout_res:
    value: 0.5
  dropout_local:
    value: 0.0
  dropout_ff:
    value: 0.0
  weight_decay:
    value: 0.1
  base_lr:
    value: 0.002

  reweigh_self:
    value: 0
  jk:
    value: 0
  init_pe_dim:
    value: 32
  more_mapping:
    value: 0
  cfg:
    value: configs/GSSC/vocsuperpixels-GSSC.yaml
  name_tag:
    value: random
  log_code:
    value: 0
  device:
    value: 0
  seed:
    values: [0, 1, 2, 3, 4]
