program: main.py
project: ZINC
entity: anonymity
name: zinc-final
method: grid
metric:
  goal: minimize
  name: best/test_mae
parameters:
  dropout_res:
    values: [0.5, 0.6]
  dropout_local:
    value: 0.0
  dropout_ff:
    value: 0.1
  weight_decay:
    value: 1.0e-5
  base_lr:
    value: 1.0e-3

  reweigh_self:
    value: 2
  jk:
    value: 1
  init_pe_dim:
    value: 32
  more_mapping:
    value: 1
  cfg:
    value: configs/GSSC/zinc-GSSC.yaml
  name_tag:
    value: random
  log_code:
    value: 0
  device:
    value: 0
  seed:
    values: [0, 1, 2, 3, 4]
