program: main.py
project: ZINC
entity: anonymity
name: zincfull-final
method: grid
metric:
  goal: minimize
  name: best/test_mae
parameters:
  dropout_res:
    values: [0.1, 0.3]
  dropout_local:
    value: 0.0
  dropout_ff:
    value: 0.1
  weight_decay:
    values: [1.0e-3, 1.0e-05]
  base_lr:
    value: 0.002

  reweigh_self:
    value: 1
  jk:
    value: 0
  init_pe_dim:
    value: 32
  more_mapping:
    value: 1
  cfg:
    value: configs/GSSC/zincfull-GSSC.yaml
  name_tag:
    value: random
  log_code:
    value: 0
  device:
    value: 0
  seed:
    values: [0, 1, 2]
